### ISSUE TITLE
Cat vs non cat dataset

### ISSUE THREAD

**Issue by adeshs95** [amanchadha/coursera-deep-learning-specialization#2]
There is a problem in loading cat vs non cat dataset.
Its giving "OSError: Unable to open file (file signature not found)" while loading dataset.
I think , the dataset is not upoaded properly.May u plz look into it.

**Comment by amanchadha** [comment]
Hi @adeshs95 ,

Can you try re-downloading it? I do not see the issues at my end. You can also get it from Coursera's DL offering.

**Comment by esasidharan** [comment]
I had the same issues : OSError and setup.sh not working.

Reason : Many files (like dataset) in this git repository are git lfs (git Large File Storage files). Reference for git lfs : https://www.atlassian.com/git/tutorials/git-lfs

When cloning a git repository with lfs files, we need to have installed git-lfs upfront in order to download the actual lfs file. Otherwise 'git clone' would download only pointers (having version, oid, size) to the lfs file. If only pointers are downloaded, 'git lfs pull' would download the lfs files.

Once all the lfs files are correctly downloaded above errors get fixed. Hope this helps others stuck with these Errors as well.

Summary
1. Make sure git-lfs is installed. Steps to install.
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
    sudo apt-get install git-lfs
2. git clone <repo_path>

If git cloned before installing git-lfs, and downloaded only pointers to lfs files, install git-lfs and then run following
git lfs pull

**Comment by amanchadha** [comment]
Thanks @esasidharan. Added these instructions to the readme: https://github.com/amanchadha/coursera-deep-learning-specialization/blob/master/README.md#cloning-instructions
