### ISSUE TITLE
not opening datasets

### ISSUE THREAD

**Issue by adeshs95** [amanchadha/coursera-deep-learning-specialization#4]
Actually , i have lost my subscription from coursera so i m not able to access this course.All the .h5 files u have uploaded is not working and giving the error "OSError: Unable to open file (file signature not found)".U can check this here "https://stackoverflow.com/questions/38089950/error-opening-file-in-h5py-file-signature-not-found".
If u may uplaod the correct files ,it will be really helpful.
Thanks in advance

**Comment by AbdielCortes** [comment]
I had the same issue, but I was able to find the datasets here:
https://github.com/Mashimo/datascience/tree/master/datasets

Just download the "train_catvnoncat.h5" and "test_catvnoncat.h5", and then exchange these files with the broken ones.

**Comment by amanchadha** [comment]
Re-uploaded:

```
        modified:   C1 - Neural Networks and Deep Learning/Week 2/Logistic Regression as a Neural Network/datasets/test_catvnoncat.h5
        modified:   C1 - Neural Networks and Deep Learning/Week 2/Logistic Regression as a Neural Network/datasets/train_catvnoncat.h5
```

Closing.

**Comment by esasidharan** [comment]
I had the same issues : OSError and setup.sh not working.

Reason : Many files (like dataset) in this git repository are git lfs (git Large File Storage files). Reference for git lfs : https://www.atlassian.com/git/tutorials/git-lfs

When cloning a git repository with lfs files, we need to have installed git-lfs upfront in order to download the actual lfs file. Otherwise 'git clone' would download only pointers (having version, oid, size) to the lfs file. If only pointers are downloaded, 'git lfs pull' would download the lfs files.

Once all the lfs files are correctly downloaded above errors get fixed. Hope this helps others stuck with these Errors as well.

Summary
1. Make sure git-lfs is installed. Steps to install.
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
    sudo apt-get install git-lfs
2. git clone <repo_path>

If git cloned before installing git-lfs, and downloaded only pointers to lfs files, install git-lfs and then run following
git lfs pull

**Comment by amanchadha** [comment]
Thanks @esasidharan. Added these instructions to the readme: https://github.com/amanchadha/coursera-deep-learning-specialization/blob/master/README.md#cloning-instructions

**Comment by esasidharan** [comment]
Thanks @amanchadha
