### ISSUE TITLE
Lower accuracy problem

### ISSUE THREAD

**Issue by ghauffrane** [amanchadha/coursera-deep-learning-specialization#5]

**Comment by ghauffrane** [comment]
Hi!
I used the same data and the same functions from the lab but i had a much lower accuracy on train set 65% and on test set 34%. I gave the model a cat pic and it predicts a non-cat. Do you have an idea on why would accuracy drop despite the fact that i used to same code and data?

**Comment by amanchadha** [comment]
I'm sorry but this is a difficult question to answer without understanding your environment.

**Comment by BJBijvoet** [comment]
The problem is that the activation values for x_test are all below 0.5 and thus y_prediction_test is 0 for every test instance. In the real y value for the test_set (test_set_y) is 0, hence the accuracy is 34%.

What helped for me is to reshape the training and test examples differently as:
train_set_x_flatten = train_set_x_orig.reshape(train_set_x_orig.shape[0], -1).T
test_set_x_flatten = test_set_x_orig.reshape(test_set_x_orig.shape[0], -1).T
